// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBGEg23cBxE1JwU_xQRgu4Nbqpl7Z7Xbbk',
    appId: '1:1014994988706:web:64a54c08b7a219dd40b1fb',
    messagingSenderId: '1014994988706',
    projectId: 'flash-chat-9b785',
    authDomain: 'flash-chat-9b785.firebaseapp.com',
    storageBucket: 'flash-chat-9b785.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDh30ctugcD2FZ8NPK9mgDtyCsN6b9s_xU',
    appId: '1:1014994988706:android:dda48bfc6034c91f40b1fb',
    messagingSenderId: '1014994988706',
    projectId: 'flash-chat-9b785',
    storageBucket: 'flash-chat-9b785.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCVg8QTUGONwvGFFmGbfiOw3Bt5YMKDguQ',
    appId: '1:1014994988706:ios:149a7d2a1ddad9a740b1fb',
    messagingSenderId: '1014994988706',
    projectId: 'flash-chat-9b785',
    storageBucket: 'flash-chat-9b785.firebasestorage.app',
    iosBundleId: 'com.example.flashChatFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCVg8QTUGONwvGFFmGbfiOw3Bt5YMKDguQ',
    appId: '1:1014994988706:ios:149a7d2a1ddad9a740b1fb',
    messagingSenderId: '1014994988706',
    projectId: 'flash-chat-9b785',
    storageBucket: 'flash-chat-9b785.firebasestorage.app',
    iosBundleId: 'com.example.flashChatFlutter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBGEg23cBxE1JwU_xQRgu4Nbqpl7Z7Xbbk',
    appId: '1:1014994988706:web:b387cf7908f4af8540b1fb',
    messagingSenderId: '1014994988706',
    projectId: 'flash-chat-9b785',
    authDomain: 'flash-chat-9b785.firebaseapp.com',
    storageBucket: 'flash-chat-9b785.firebasestorage.app',
  );
}
